controllers/PageController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use app\models\Page;
use yii\web\NotFoundHttpException;

class PageController extends Controller 
{

	public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                //'only' => ['logout'],
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'allow' => false,
                    ]
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

	public function actionIndex()
	{
		$model = new Page();
		return $this->render('index', [
			'model' => $model,
		]);
	}	

	public function actionUpdate($id) 
	{
		$model = $this->loadModel($id);
		
		$data = Yii::$app->request->post();
		if($model->load($data) && $model->save()) {
			$this->redirect(['view', 'id' => (string)$model->_id]);
		}

		return $this->render('update', ['model' => $model]);
	}

	public function actionCreate()
	{
		$model = new Page();

		$data = Yii::$app->request->post();
		if($model->load($data) && $model->save()) {
			$this->redirect(['view', 'id' => (string)$model->_id]);
		}

		return $this->render('create', ['model' => $model]);
	}

	public function actionView($id)
	{
		$model = $this->loadModel($id);
		return $this->render('view', [
			'model' => $model,
		]);
	}

	public function actionDelete($id)
	{
		if($this->loadModel($id)->delete()) {
			$this->redirect(['index']);
		}
	}

	private function loadModel($id)
	{
		$model = Page::findOne($id);
		if(!$model) {
			throw new NotFoundHttpException();
		}
		return $model;
	}
}

views/page/_form.php
<?php
use \yii\redactor\widgets\Redactor;
use \yii\helpers\Html;
use \yii\widgets\ActiveForm; 
?>

<?php $form = ActiveForm::begin(); ?> 

<?= $form->errorSummary($model) ?>

<?= $form->field($model, 'active')->checkbox() ?>

<?= $form->field($model, 'name') ?>

<?= $form->field($model, 'order') ?>

<?= $form->field($model, 'icon') ?>

<?= $form->field($model, 'markdown')->textArea(['rows' => 15]) ?>

<?= $form->field($model, 'html')->widget(Redactor::className(), ['clientOptions' => [
	'minHeight' => 200,
]]) ?>

<div class="form-group">
	<?= Html::submitButton('Submit', ['class' => 'btn btn-primary']) ?> 
</div>

views/page/create.php
<?php
$this->params['breadcrumbs'] = [
	['label' => 'Pages',  'url' => ['page/index']],
	['label' => 'Create'],
];
?>
<h1>Create new Page</h1>

<?= $this->render('_form', ['model' => $model]) ?>

views/page/index.php
<?php
use yii\grid\GridView;
use yii\grid\ActionColumn;
use yii\data\ActiveDataProvider;
use app\models\Page;
use yii\helpers\Html;

$this->params['breadcrumbs'] = [
    ['label' => 'Pages'],
];

?>

<h1>Page Overview</h1>

<?= Html::a('Create', ['create'], ['class' => 'btn btn-primary']) ?>
<br /><br />
<?php

$dataProvider = new ActiveDataProvider([
    'query' => Page::find(),
    'pagination' => [
        'pageSize' => 20,
    ],
]);
echo GridView::widget([
    'dataProvider' => $dataProvider,
    'columns' => [
    	'name',
        'order',
    	[
    		'class' => ActionColumn::className(),
    	],
    ],
]);

views/page/update.php
<?php
$this->params['breadcrumbs'] = [
	['label' => 'Pages',  'url' => ['page/index']],
	['label' => 'View: ' . $model->name, 'url' => ['page/view', 'id' => (string)$model->_id]],
	['label' => 'Update'],
];
?>
<h1>Update Page <?= $model->name ?></h1>

<?= $this->render('_form', ['model' => $model]) ?>

views/page/view.php
<?php
use yii\helpers\Html;

$this->params['breadcrumbs'] = [
	['label' => 'Pages',  'url' => ['page/index']],
	['label' => 'View: ' . $model->name],
];
?>

<h1>View Page: <?= $model->name ?> <?= !$model->active ? "(inactive)" : "" ?></h1>

<?= Html::a('Update', ['update', 'id' => (string)$model->_id], ['class' => 'btn btn-primary']) ?> 
<?= Html::a('Create', ['create', 'id' => (string)$model->_id], ['class' => 'btn btn-default']) ?>

<br />
<br />
<strong>Icon:</strong> <?= $model->icon ?><br />

<h2>HTML</h2>
<?= $model->html ?>

<h2>Markdown</h2>
<pre>
<?= $model->markdown ?>
</pre>